
package view;

import dao.LibroDAO;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;


public class Ventana extends javax.swing.JFrame {

    private CardLayout cl;
    private Connection conn;
    /** Creates new form Ventana
     * @param conn */
    public Ventana(Connection conn) {
        initComponents();
        this.conn = conn;
        this.cl = (CardLayout) this.panelPrincipal.getLayout();
        this.cl.show(this.panelPrincipal,"panelMenuPrincipal");
        cargarLibrosPanel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelNombreDni = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTituloIngresoDatos = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        panelMostrarPrestamos = new javax.swing.JPanel();
        scrollPanePrestamos = new javax.swing.JScrollPane();
        txtaPrestamos = new javax.swing.JTextArea();
        btnVolverMenu = new javax.swing.JButton();
        panelMenuPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnPedirPrestamos = new javax.swing.JButton();
        btnMostrarPrestamos = new javax.swing.JButton();
        panelLibros = new javax.swing.JPanel();
        scrollPaneLibros = new javax.swing.JScrollPane();
        panelCheckboxes = new javax.swing.JPanel();
        lblEleccionLibros = new javax.swing.JLabel();
        btnEleccionLibros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.CardLayout());

        txtNombre.setColumns(20);

        txtDNI.setColumns(15);

        lblDni.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblDni.setText("DNI:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblTituloIngresoDatos.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTituloIngresoDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloIngresoDatos.setText("Ingrese sus datos");

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNombreDniLayout = new javax.swing.GroupLayout(panelNombreDni);
        panelNombreDni.setLayout(panelNombreDniLayout);
        panelNombreDniLayout.setHorizontalGroup(
            panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreDniLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNombreDniLayout.createSequentialGroup()
                        .addComponent(btnIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addComponent(lblTituloIngresoDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNombreDniLayout.createSequentialGroup()
                        .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );
        panelNombreDniLayout.setVerticalGroup(
            panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreDniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloIngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnVolver))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelNombreDni, "panelNombreDni");

        txtaPrestamos.setEditable(false);
        txtaPrestamos.setColumns(20);
        txtaPrestamos.setRows(5);
        scrollPanePrestamos.setViewportView(txtaPrestamos);

        btnVolverMenu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnVolverMenu.setText("Volver al Menu Principal");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMostrarPrestamosLayout = new javax.swing.GroupLayout(panelMostrarPrestamos);
        panelMostrarPrestamos.setLayout(panelMostrarPrestamosLayout);
        panelMostrarPrestamosLayout.setHorizontalGroup(
            panelMostrarPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanePrestamos)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrarPrestamosLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(btnVolverMenu)
                .addGap(97, 97, 97))
        );
        panelMostrarPrestamosLayout.setVerticalGroup(
            panelMostrarPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanePrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolverMenu)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelMostrarPrestamos, "panelMostrarPrestamos");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Prestamos de Libros");

        btnPedirPrestamos.setText("Pedir Prestamos");
        btnPedirPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirPrestamosActionPerformed(evt);
            }
        });

        btnMostrarPrestamos.setText("Mostrar Prestamos");
        btnMostrarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPrestamosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuPrincipalLayout = new javax.swing.GroupLayout(panelMenuPrincipal);
        panelMenuPrincipal.setLayout(panelMenuPrincipalLayout);
        panelMenuPrincipalLayout.setHorizontalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                        .addComponent(btnPedirPrestamos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarPrestamos))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        panelMenuPrincipalLayout.setVerticalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedirPrestamos)
                    .addComponent(btnMostrarPrestamos))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelMenuPrincipal, "panelMenuPrincipal");

        javax.swing.GroupLayout panelCheckboxesLayout = new javax.swing.GroupLayout(panelCheckboxes);
        panelCheckboxes.setLayout(panelCheckboxesLayout);
        panelCheckboxesLayout.setHorizontalGroup(
            panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );
        panelCheckboxesLayout.setVerticalGroup(
            panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        scrollPaneLibros.setViewportView(panelCheckboxes);

        lblEleccionLibros.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblEleccionLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEleccionLibros.setText("Elige los libros");

        btnEleccionLibros.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEleccionLibros.setText("Eleccion");

        javax.swing.GroupLayout panelLibrosLayout = new javax.swing.GroupLayout(panelLibros);
        panelLibros.setLayout(panelLibrosLayout);
        panelLibrosLayout.setHorizontalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblEleccionLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(btnEleccionLibros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLibrosLayout.setVerticalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEleccionLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnEleccionLibros)
                .addContainerGap())
        );

        panelPrincipal.add(panelLibros, "panelLibros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedirPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirPrestamosActionPerformed
        this.cl.show(this.panelPrincipal,"panelNombreDni");
    }//GEN-LAST:event_btnPedirPrestamosActionPerformed

    private void btnMostrarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPrestamosActionPerformed
        while(true){
            String input = JOptionPane.showInputDialog("Ingrese su DNI:");

            if (input == null) {
                // El usuario canceló
                JOptionPane.showMessageDialog(null, "Operación cancelada.");
                return;
            }
            try{
                int dni = Integer.parseInt(input.trim());
                
                this.cl.show(this.panelPrincipal,"panelMostrarPrestamos");
                break;
            }catch(NumberFormatException e){
                System.out.println("No ingreso un numero");
            }
        }
    }//GEN-LAST:event_btnMostrarPrestamosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.cl.show(this.panelPrincipal,"panelMenuPrincipal");
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        this.cl.show(this.panelPrincipal,"panelMenuPrincipal");
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        this.cl.show(this.panelPrincipal,"panelLibros");
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void cargarLibrosPanel(){
        ArrayList<String> libros = LibroDAO.buscarNombreLibro(this.conn);
        this.panelCheckboxes.setLayout(new BoxLayout(panelCheckboxes,BoxLayout.Y_AXIS));
        for(String libro: libros){
            JCheckBox jcb = new JCheckBox(libro);
            jcb.setAlignmentX(Component.LEFT_ALIGNMENT);
            this.panelCheckboxes.add(jcb);
            this.panelCheckboxes.add(Box.createVerticalStrut(5)); // Separación de 5px
        }
        panelCheckboxes.revalidate(); // Recalcula el layout
        panelCheckboxes.repaint();    // Redibuja el panel
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEleccionLibros;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnMostrarPrestamos;
    private javax.swing.JButton btnPedirPrestamos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEleccionLibros;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloIngresoDatos;
    private javax.swing.JPanel panelCheckboxes;
    private javax.swing.JPanel panelLibros;
    private javax.swing.JPanel panelMenuPrincipal;
    private javax.swing.JPanel panelMostrarPrestamos;
    private javax.swing.JPanel panelNombreDni;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollPaneLibros;
    private javax.swing.JScrollPane scrollPanePrestamos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtaPrestamos;
    // End of variables declaration//GEN-END:variables

}
