
package view;

import dao.LibroDAO;
import dao.PersonaDAO;
import dao.PrestamoDAO;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import model.Libro;
import model.Persona;
import model.Prestamo;


public class Ventana extends javax.swing.JFrame {

    private CardLayout cl;
    private Connection conn;
    Persona persona; //Variables temporales para crear en el momento
    Prestamo prestamo;
    
    /** Creates new form Ventana
     * @param conn */
    public Ventana(Connection conn) {
        initComponents();
        this.conn = conn;
        this.cl = (CardLayout) this.panelPrincipal.getLayout();
        this.cl.show(this.panelPrincipal,"panelMenuPrincipal");
        cargarLibrosPanel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        panelPrincipal = new javax.swing.JPanel();
        panelNombreDni = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTituloIngresoDatos = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        panelMostrarPrestamos = new javax.swing.JPanel();
        scrollPanePrestamos = new javax.swing.JScrollPane();
        txtaPrestamos = new javax.swing.JTextArea();
        btnVolverMenu = new javax.swing.JButton();
        panelLibros = new javax.swing.JPanel();
        scrollPaneLibros = new javax.swing.JScrollPane();
        panelCheckboxes = new javax.swing.JPanel();
        lblEleccionLibros = new javax.swing.JLabel();
        btnEleccionLibros = new javax.swing.JButton();
        panelMenuPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnPedirPrestamos = new javax.swing.JButton();
        btnMostrarPrestamos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.CardLayout());

        txtNombre.setColumns(20);

        txtDNI.setColumns(15);

        lblDni.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblDni.setForeground(new java.awt.Color(255, 255, 255));
        lblDni.setText("DNI:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");

        lblTituloIngresoDatos.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTituloIngresoDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloIngresoDatos.setText("Ingrese sus datos");

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNombreDniLayout = new javax.swing.GroupLayout(panelNombreDni);
        panelNombreDni.setLayout(panelNombreDniLayout);
        panelNombreDniLayout.setHorizontalGroup(
            panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreDniLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNombreDniLayout.createSequentialGroup()
                        .addComponent(btnIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addComponent(lblTituloIngresoDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNombreDniLayout.createSequentialGroup()
                        .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );
        panelNombreDniLayout.setVerticalGroup(
            panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreDniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloIngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelNombreDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnVolver))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelNombreDni, "panelNombreDni");

        txtaPrestamos.setEditable(false);
        txtaPrestamos.setColumns(20);
        txtaPrestamos.setRows(5);
        scrollPanePrestamos.setViewportView(txtaPrestamos);

        btnVolverMenu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverMenu.setText("Volver al Menu Principal");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMostrarPrestamosLayout = new javax.swing.GroupLayout(panelMostrarPrestamos);
        panelMostrarPrestamos.setLayout(panelMostrarPrestamosLayout);
        panelMostrarPrestamosLayout.setHorizontalGroup(
            panelMostrarPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanePrestamos)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrarPrestamosLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(btnVolverMenu)
                .addGap(97, 97, 97))
        );
        panelMostrarPrestamosLayout.setVerticalGroup(
            panelMostrarPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanePrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolverMenu)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelMostrarPrestamos, "panelMostrarPrestamos");

        panelLibros.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCheckboxesLayout = new javax.swing.GroupLayout(panelCheckboxes);
        panelCheckboxes.setLayout(panelCheckboxesLayout);
        panelCheckboxesLayout.setHorizontalGroup(
            panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );
        panelCheckboxesLayout.setVerticalGroup(
            panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        scrollPaneLibros.setViewportView(panelCheckboxes);

        lblEleccionLibros.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblEleccionLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEleccionLibros.setText("Elige los libros");

        btnEleccionLibros.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEleccionLibros.setForeground(new java.awt.Color(255, 255, 255));
        btnEleccionLibros.setText("Eleccion");
        btnEleccionLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleccionLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLibrosLayout = new javax.swing.GroupLayout(panelLibros);
        panelLibros.setLayout(panelLibrosLayout);
        panelLibrosLayout.setHorizontalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblEleccionLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(btnEleccionLibros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLibrosLayout.setVerticalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEleccionLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnEleccionLibros)
                .addContainerGap())
        );

        panelPrincipal.add(panelLibros, "panelLibros");

        panelMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Prestamos de Libros");

        btnPedirPrestamos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnPedirPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnPedirPrestamos.setText("Pedir Prestamos");
        btnPedirPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirPrestamosActionPerformed(evt);
            }
        });

        btnMostrarPrestamos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnMostrarPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarPrestamos.setText("Mostrar Prestamos");
        btnMostrarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPrestamosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuPrincipalLayout = new javax.swing.GroupLayout(panelMenuPrincipal);
        panelMenuPrincipal.setLayout(panelMenuPrincipalLayout);
        panelMenuPrincipalLayout.setHorizontalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(btnPedirPrestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarPrestamos)
                .addGap(50, 50, 50))
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        panelMenuPrincipalLayout.setVerticalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedirPrestamos)
                    .addComponent(btnMostrarPrestamos))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelMenuPrincipal, "panelMenuPrincipal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedirPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirPrestamosActionPerformed
        this.cl.show(this.panelPrincipal,"panelNombreDni");
    }//GEN-LAST:event_btnPedirPrestamosActionPerformed

    /**
     * Metodo del boton que revisa si el dni ingresado es un entero. De ser asi
     * se llama al metodo mostrarPrestamos que se encarga de imprimirlos en pantalla.
     * Por ultimo cambia el panelPrincipal para mostrar el panel donde se imprimen los prestamos
     * @param evt 
     */
    private void btnMostrarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPrestamosActionPerformed
        while(true){
            String input = JOptionPane.showInputDialog("Ingrese su DNI:");

            if (input == null) {
                // El usuario canceló
                JOptionPane.showMessageDialog(null, "Operación cancelada.");
                return;
            }
            try{
                int dni = Integer.parseInt(input.trim());
                mostrarPrestamos(dni);
                this.cl.show(this.panelPrincipal,"panelMostrarPrestamos");
                break;
            }catch(NumberFormatException e){
                System.out.println("No ingreso un numero");
            }
        }
    }//GEN-LAST:event_btnMostrarPrestamosActionPerformed

    /**
     * Muestra en el JTextArea del panelMostrarPrestamos, el metodo toString de el prestamo
     * que realizo la persona con el dni ingresado.
     * @param dni - dni de la persona 
     */
    private void mostrarPrestamos(int dni) {
        this.txtaPrestamos.setText("");
        Prestamo p = PrestamoDAO.buscarPrestamoPorDni(conn, dni);
        // Debug adicional
        if(p != null) {
            System.out.println("Préstamo encontrado ID: " + p.id);
            System.out.println("Número de libros: " + (p.librosEscritos != null ? p.librosEscritos.size() : 0));
        }
        this.txtaPrestamos.setText(p.toString());
    }
    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.cl.show(this.panelPrincipal,"panelMenuPrincipal");
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        this.cl.show(this.panelPrincipal,"panelMenuPrincipal");
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    /**
     * Metodo para insertar la persona ingresada. Verifica si los campos no estan vacios.
     * Inserta una persona a la base de datos siempre y cuando no exista en la base de datos
     * anteriormente. 
     * @param evt 
     */
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if(this.txtDNI.getText().isEmpty() || this.txtNombre.getText().isEmpty())return;
        try{
            int dni = Integer.parseInt(this.txtDNI.getText());
            
            String nombre = this.txtNombre.getText();
            if ( PersonaDAO.existeDni(conn, dni)){
                JOptionPane.showMessageDialog(null, "Esa persona ya existe");
                return;
            }
            this.persona = new Persona(dni,nombre);
            PersonaDAO.insertarPersona(conn,this.persona);
            this.prestamo = new Prestamo();
            this.prestamo.setSocio(persona);
        }catch(NumberFormatException e){
            System.out.println("El dni tiene que ser un numero");
        }
        this.cl.show(this.panelPrincipal,"panelLibros");
        this.txtDNI.setText("");
        this.txtNombre.setText("");
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * Verifica cuales JCheckbox fueron seleccionados, creando un arreglo de libros
     * que luego seran insertados en el objeto Prestamo que fue creado en btnIngresarActionPerformed
     * @param evt 
     */
    private void btnEleccionLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionLibrosActionPerformed
        for (Component comp : this.panelCheckboxes.getComponents()){
            if(comp instanceof JCheckBox chbx){
                if(chbx.isSelected()){
                    Libro libro = LibroDAO.buscarLibroPorNombre(conn,chbx.getText());
                    if (libro != null) { // Verificar que el libro existe
                    this.prestamo.agregarLibro(libro);}
                    chbx.setSelected(false);
                }
            }
        }
        PrestamoDAO.insertarPrestamo(conn, prestamo);
        JOptionPane.showMessageDialog(null, "Prestamo ingresado correctamente");
        this.cl.show(this.panelPrincipal, "panelMenuPrincipal");
    }//GEN-LAST:event_btnEleccionLibrosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEleccionLibros;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnMostrarPrestamos;
    private javax.swing.JButton btnPedirPrestamos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEleccionLibros;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloIngresoDatos;
    private javax.swing.JPanel panelCheckboxes;
    private javax.swing.JPanel panelLibros;
    private javax.swing.JPanel panelMenuPrincipal;
    private javax.swing.JPanel panelMostrarPrestamos;
    private javax.swing.JPanel panelNombreDni;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollPaneLibros;
    private javax.swing.JScrollPane scrollPanePrestamos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtaPrestamos;
    // End of variables declaration//GEN-END:variables

    /**
     * Muestra en el nombre de los libros que hay en la base de datos en forma de JCheckbox.
     */
    private void cargarLibrosPanel(){
        ArrayList<String> libros = LibroDAO.buscarNombreLibro(this.conn);
        this.panelCheckboxes.setLayout(new BoxLayout(panelCheckboxes,BoxLayout.Y_AXIS));
        for(String tituloLibro: libros){
            JCheckBox jcb = new JCheckBox(tituloLibro);
            jcb.setAlignmentX(Component.LEFT_ALIGNMENT);
            this.panelCheckboxes.add(jcb);
            this.panelCheckboxes.add(Box.createVerticalStrut(5)); // Separación de 5px
        }
        panelCheckboxes.revalidate(); // Recalcula el layout
        panelCheckboxes.repaint();    // Redibuja el panel
    }
}
